sudo: required
dist: trusty
language: node_js

node_js:
  - 6

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

after_script:
 - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js

addons:
    code_climate:
        repo_token: aeb35c62c464d1aca611432871f81a5827525f2f86735e8146207b9923ec4e3a
